parameters:
    cassandra.nodes: host=host;port=9160
    cassandra.keyspace: minecraft_md

services:
    mmd.cassandra:
        class:      Mmd\CassandraBundle\Service\Cassandra
        arguments:  [%cassandra.nodes%, %cassandra.keyspace%]
