parameters:
    mmd.cassandra.nodes: host=localhost;port=9160
    mmd.cassandra.keyspace: my_keyspace

services:
    mmd.cassandra:
        class:      Mmd\Bundle\CassandraBundle\Service\Cassandra
        arguments:  [%mmd.cassandra.nodes%, %mmd.cassandra.keyspace%]
