parameters:
    mmd.cassandra.nodes: host=localhost;port=9160
    mmd.cassandra.keyspace: my_keyspace

services:
    mmd.cassandra_pdo:
        class:      Mmd\Bundle\CassandraBundle\Service\CassandraPDO
        arguments:  [%mmd.cassandra.nodes%, %mmd.cassandra.keyspace%]
