parameters:
    cassandra.nodes: host=localhost;port=9160
    cassandra.keyspace: minecraft_md

services:
    cassandra:
        class:      Mmd\CassandraBundle\Service\Cassandra
        arguments:  [%cassandra.nodes%, %cassandra.keyspace%]
